/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class engine_GaviotaEGTB */

#ifndef _Included_engine_GaviotaEGTB
#define _Included_engine_GaviotaEGTB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     engine_GaviotaEGTB
 * Method:    init
 * Signature: ([Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_engine_GaviotaEGTB_init
  (JNIEnv *, jclass, jobjectArray, jlong);

/*
 * Class:     engine_GaviotaEGTB
 * Method:    availability
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_engine_GaviotaEGTB_availability
  (JNIEnv *, jclass);

/*
 * Class:     engine_GaviotaEGTB
 * Method:    probeDTM
 * Signature: (ZII[I[I[B[B[I)I
 */
JNIEXPORT jint JNICALL Java_engine_GaviotaEGTB_probeDTM
  (JNIEnv *, jclass, jboolean, jint, jint, jintArray, jintArray, jbyteArray, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
